import { expect, test } from '@playwright/test'

test('Reveal reuses the Part 01 geometry and balances two equal videos', async ({ page }) => {
  await page.setViewportSize({ width: 2560, height: 1080 })
  await page.goto('/experiment/00/part-01')

  const partTitleBounds = await page.locator('.part-title').boundingBox()
  const partVideoBounds = await page.locator('.video-placeholder').boundingBox()

  await page.goto('/experiment/00/part-01/reveal')
  const revealTitle = page.getByRole('heading', { name: 'PART 01 : REVEAL' })
  const revealVideos = page.locator('.reveal-media .video-placeholder')
  const subjectLabels = page.locator('.reveal-subject-label')
  await expect(revealTitle).toBeVisible()
  await expect(revealVideos).toHaveCount(2)
  await expect(subjectLabels).toHaveText(['SUBJECT 1', 'SUBJECT 2'])
  await expect(page.locator('.timestamps')).toHaveCount(0)
  await expect(page.getByText('WATCHED THE VIDEO?', { exact: true })).toHaveCount(0)

  const revealTitleBounds = await revealTitle.boundingBox()
  const leftVideoBounds = await revealVideos.nth(0).boundingBox()
  const rightVideoBounds = await revealVideos.nth(1).boundingBox()
  const subjectOneBounds = await subjectLabels.nth(0).boundingBox()
  const subjectTwoBounds = await subjectLabels.nth(1).boundingBox()

  expect(revealTitleBounds.x).toBeCloseTo(partTitleBounds.x + (partTitleBounds.width - revealTitleBounds.width) / 2, 0)
  expect(revealTitleBounds.y).toBeCloseTo(partTitleBounds.y, 0)
  expect(leftVideoBounds.x).toBeCloseTo(partVideoBounds.x, 0)
  expect(leftVideoBounds.y).toBeCloseTo(partVideoBounds.y, 0)
  expect(leftVideoBounds.width).toBeCloseTo(partVideoBounds.width, 0)
  expect(leftVideoBounds.height).toBeCloseTo(partVideoBounds.height, 0)
  expect(rightVideoBounds.y).toBeCloseTo(leftVideoBounds.y, 0)
  expect(rightVideoBounds.width).toBeCloseTo(leftVideoBounds.width, 0)
  expect(rightVideoBounds.height).toBeCloseTo(leftVideoBounds.height, 0)
  expect(leftVideoBounds.width / leftVideoBounds.height).toBeCloseTo(16 / 9, 2)
  expect(leftVideoBounds.x).toBeCloseTo(2560 - rightVideoBounds.x - rightVideoBounds.width, 0)
  expect(rightVideoBounds.x).toBeGreaterThan(leftVideoBounds.x + leftVideoBounds.width)
  expect(subjectOneBounds.x + subjectOneBounds.width / 2)
    .toBeCloseTo(leftVideoBounds.x + leftVideoBounds.width / 2, 0)
  expect(subjectTwoBounds.x + subjectTwoBounds.width / 2)
    .toBeCloseTo(rightVideoBounds.x + rightVideoBounds.width / 2, 0)
  expect(subjectOneBounds.y + subjectOneBounds.height).toBeLessThan(leftVideoBounds.y)
  expect(subjectTwoBounds.y + subjectTwoBounds.height).toBeLessThan(rightVideoBounds.y)
  expect(subjectOneBounds.height).toBeLessThan(revealTitleBounds.height)

  await page.getByRole('button', { name: 'FR', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'PARTIE 01 : RÉSULTATS' })).toBeVisible()
  await expect(subjectLabels).toHaveText(['SUJET 1', 'SUJET 2'])
  await page.getByRole('button', { name: 'BLACK', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'black')

  const continueLink = page.getByRole('link', { name: /CONTINUER/ })
  await expect(continueLink).toHaveAttribute('href', '/experiment/00/part-01/end')
  const continueBounds = await continueLink.boundingBox()
  expect(await page.evaluate(() => document.documentElement.scrollHeight)).toBeGreaterThan(1080)
  expect(continueBounds.x + continueBounds.width).toBeGreaterThan(2560 * 0.9)
  expect(continueBounds.y).toBeGreaterThan(rightVideoBounds.y + rightVideoBounds.height)
  await continueLink.scrollIntoViewIfNeeded()
  const visibleContinueBounds = await continueLink.boundingBox()
  expect(visibleContinueBounds.y + visibleContinueBounds.height).toBeLessThanOrEqual(1080)
  await continueLink.click()
  await expect(page).toHaveURL(/\/experiment\/00\/part-01\/end$/)
})

test('Reveal stacks its 16:9 videos without mobile overflow', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 667 })
  await page.goto('/experiment/00/part-01/reveal')

  const videos = page.locator('.reveal-media .video-placeholder')
  const subjectLabels = page.locator('.reveal-subject-label')
  await expect(videos).toHaveCount(2)
  await expect(subjectLabels).toHaveText(['SUBJECT 1', 'SUBJECT 2'])
  const first = await videos.first().boundingBox()
  const second = await videos.last().boundingBox()
  expect(second.y).toBeGreaterThan(first.y + first.height)
  const secondLabel = await subjectLabels.last().boundingBox()
  expect(secondLabel.y + secondLabel.height).toBeLessThan(second.y)
  expect(first.width / first.height).toBeCloseTo(16 / 9, 2)
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(375)
})
